### ISSUE TITLE
MARTINHO: Nota de compra não finaliza.

### ISSUE THREAD

**Issue by SupportWR** [wagnerra23/Office-Impresso#12]
Removido Produto: 23T06/132 
Nota finalizada.
O item sozinho na nota funciona. Com mais itens, impossível finalizar.

**Comment by felipesfx** [comment]
> ajustado o inicio e fim da transaction
> 
> https://github.com/wagnerra23/Office-Impresso/blob/f1adb3e40071307d545bb5e1358b73867fce472f/app/Services/Services.Compra.pas#L35-L99

**Comment by felipesfx** [comment]
@wagnerra23 foi removido transações dentro dessa rotina: https://github.com/wagnerra23/Office-Impresso/blob/f1adb3e40071307d545bb5e1358b73867fce472f/app/Services/Services.Compra.pas#L63-L69
